# Generated by Django 4.2.7 on 2023-12-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.IntegerField()),
                ('applicant', models.CharField(max_length=255)),
                ('facilitytype', models.CharField(blank=True, choices=[('Push Cart', 'Push Cart'), ('Truck', 'Truck')], default='Truck', max_length=9, null=True)),
                ('cnn', models.IntegerField()),
                ('locationdescription', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('blocklot', models.CharField(max_length=255)),
                ('block', models.CharField(max_length=255)),
                ('lot', models.CharField(max_length=255)),
                ('permit', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('REQUESTED', 'REQUESTED'), ('SUSPEND', 'SUSPEND'), ('EXPIRED', 'EXPIRED')], default='REQUESTED', max_length=9)),
                ('fooditems', models.CharField(max_length=255)),
                ('x', models.CharField(blank=True, max_length=255, null=True)),
                ('y', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('schedule', models.URLField(blank=True, null=True)),
                ('dayshours', models.CharField(blank=True, max_length=255, null=True)),
                ('noisent', models.CharField(blank=True, max_length=255, null=True)),
                ('approved', models.CharField(blank=True, max_length=255, null=True)),
                ('received', models.CharField(blank=True, max_length=255, null=True)),
                ('priorpermit', models.CharField(blank=True, max_length=255, null=True)),
                ('expirationdate', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('fire_prevention_districts', models.CharField(blank=True, max_length=255, null=True)),
                ('police_districts', models.CharField(blank=True, max_length=255, null=True)),
                ('supervisor_districts', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_codes', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhoods_old', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
